#let jp-region = (
  hokkaido: "JP01",
  aomori: "JP02",
  iwate: "JP03",
  miyagi: "JP04",
  akita: "JP05",
  yamagata: "JP06",
  fukushima: "JP07",
  ibaraki: "JP08",
  tochigi: "JP09",
  gunma: "JP10",
  saitama: "JP11",
  chiba: "JP12",
  tokyo: "JP13",
  kanagawa: "JP14",
  niigata: "JP15",
  toyama: "JP16",
  ishikawa: "JP17",
  fukui: "JP18",
  yamanashi: "JP19",
  nagano: "JP20",
  gifu: "JP21",
  shizuoka: "JP22",
  aichi: "JP23",
  mie: "JP24",
  shiga: "JP25",
  kyoto: "JP26",
  osaka: "JP27",
  hyogo: "JP28",
  nara: "JP29",
  wakayama: "JP30",
  tottori: "JP31",
  shimane: "JP32",
  okayama: "JP33",
  hiroshima: "JP34",
  yamaguchi: "JP35",
  tokushima: "JP36",
  kagawa: "JP37",
  ehime: "JP38",
  kochi: "JP39",
  fukuoka: "JP40",
  saga: "JP41",
  nagasaki: "JP42",
  kumamoto: "JP43",
  oita: "JP44",
  miyazaki: "JP45",
  kagoshima: "JP46",
  okinawa: "JP47",
)

#let companies = (
  JR北海道: (
    fill: "#00a1e4",
    coverage: (
      jp-region.hokkaido,
      jp-region.aomori,
    ),
  ),
  JR東日本: (
    fill: "#22ac38",
    coverage: (
      jp-region.akita,
      jp-region.aomori,
      jp-region.chiba,
      jp-region.fukushima,
      jp-region.gunma,
      jp-region.ibaraki,
      jp-region.iwate,
      jp-region.kanagawa,
      jp-region.miyagi,
      jp-region.nagano,
      jp-region.niigata,
      jp-region.saitama,
      jp-region.shizuoka,
      jp-region.tochigi,
      jp-region.tokyo,
      jp-region.yamagata,
      jp-region.yamanashi,
    ),
  ),
  JR東海: (
    fill: "#ff6600",
    coverage: (
      jp-region.aichi,
      jp-region.gifu,
      jp-region.kanagawa,
      jp-region.kyoto,
      jp-region.mie,
      jp-region.nagano,
      jp-region.osaka,
      jp-region.shiga,
      jp-region.shizuoka,
      jp-region.tokyo,
      jp-region.yamanashi,
    ),
  ),
  JR西日本: (
    fill: "#0067b1",
    coverage: (
      jp-region.fukui,
      jp-region.fukuoka,
      jp-region.hiroshima,
      jp-region.hyogo,
      jp-region.ishikawa,
      jp-region.kyoto,
      jp-region.mie,
      jp-region.nagano,
      jp-region.nara,
      jp-region.niigata,
      jp-region.okayama,
      jp-region.osaka,
      jp-region.shiga,
      jp-region.shimane,
      jp-region.tottori,
      jp-region.toyama,
      jp-region.wakayama,
      jp-region.yamaguchi,
    ),
  ),
  JR四国: (
    fill: "#00aca5",
    coverage: (
      jp-region.ehime,
      jp-region.kagawa,
      jp-region.kochi,
      jp-region.okayama,
      jp-region.tokushima,
    ),
  ),
  JR九州: (
    fill: "#f62e31",
    coverage: (
      jp-region.fukuoka,
      jp-region.kagoshima,
      jp-region.kumamoto,
      jp-region.miyazaki,
      jp-region.nagasaki,
      jp-region.oita,
      jp-region.saga,
      jp-region.yamaguchi,
    ),
  ),
  JR総研: (
    fill: "#c7b299",
    coverage: (),
  ),
  JR貨物: (
    fill: "#003399",
    coverage: {
      let c = jp-region
      let _ = c.remove("okinawa")
      c.values()
    },
  ),
  メーカ・試作: (
    fill: "#7f7f7f",
    coverage: (),
  ),
  九州: (
    fill: "#f62e31",
    coverage: (
      jp-region.fukuoka,
      jp-region.saga,
      jp-region.nagasaki,
      jp-region.kumamoto,
      jp-region.oita,
      jp-region.miyazaki,
      jp-region.kagoshima,
      jp-region.okinawa,
    ),
  ),
  京急: (
    fill: "#e60012",
    coverage: (jp-region.tokyo, jp-region.kanagawa),
  ),
  京成系・関鉄: (
    fill: "#004098",
    coverage: (jp-region.tokyo, jp-region.chiba, jp-region.ibaraki),
  ),
  京王: (
    fill: "#dd0077",
    coverage: (jp-region.tokyo, jp-region.kanagawa),
  ),
  京阪・叡電・嵐電: (
    fill: "#00693e",
    coverage: (jp-region.kyoto, jp-region.osaka, jp-region.shiga),
  ),
  北海道: (
    fill: "#00a1e4",
    coverage: (jp-region.hokkaido,),
  ),
  北陸: (
    fill: "#00a3af",
    coverage: (jp-region.fukui, jp-region.ishikawa, jp-region.toyama, jp-region.niigata),
  ),
  南海・阪堺: (
    fill: "#0f7143",
    coverage: (jp-region.osaka, jp-region.wakayama),
  ),
  名鉄・豊鉄: (
    fill: "#cc0022",
    coverage: (jp-region.aichi, jp-region.gifu),
  ),
  四国: (
    fill: "#00aca5",
    coverage: (jp-region.kagawa, jp-region.ehime, jp-region.kochi, jp-region.tokushima),
  ),
  大阪メトロ・北急: (
    fill: "#0083ca",
    coverage: (jp-region.osaka,),
  ),
  小田急系: (
    fill: "#0067b1",
    coverage: (jp-region.tokyo, jp-region.kanagawa, jp-region.shizuoka),
  ),
  山陽山陰: (
    fill: "#00533e",
    coverage: (jp-region.okayama, jp-region.hiroshima, jp-region.yamaguchi, jp-region.tottori, jp-region.shimane),
  ),
  新幹線: (
    fill: "#003399",
    coverage: (
      jp-region.hokkaido,
      jp-region.aomori,
      jp-region.iwate,
      jp-region.miyagi,
      jp-region.akita,
      jp-region.yamagata,
      jp-region.fukushima,
      jp-region.ibaraki,
      jp-region.tochigi,
      jp-region.gunma,
      jp-region.saitama,
      jp-region.tokyo,
      jp-region.kanagawa,
      jp-region.niigata,
      jp-region.toyama,
      jp-region.ishikawa,
      jp-region.fukui,
      jp-region.yamanashi,
      jp-region.nagano,
      jp-region.gifu,
      jp-region.shizuoka,
      jp-region.aichi,
      jp-region.mie,
      jp-region.shiga,
      jp-region.kyoto,
      jp-region.osaka,
      jp-region.hyogo,
      jp-region.nara,
      jp-region.okayama,
      jp-region.hiroshima,
      jp-region.yamaguchi,
      jp-region.fukuoka,
      jp-region.saga,
      jp-region.nagasaki,
      jp-region.kumamoto,
      jp-region.kagoshima,
    ),
  ),
  旧国鉄優等: (
    fill: "#bf0000",
    coverage: {
      let c = jp-region
      let _ = c.remove("okinawa")
      c.values()
    },
  ),
  旧国鉄: (
    fill: "#555555",
    coverage: {
      let c = jp-region
      let _ = c.remove("okinawa")
      c.values()
    },
  ),
  東京メトロ: (
    fill: "#009bb4",
    coverage: (jp-region.tokyo, jp-region.chiba, jp-region.saitama),
  ),
  東北: (
    fill: "#1e50a2",
    coverage: (
      jp-region.aomori,
      jp-region.iwate,
      jp-region.miyagi,
      jp-region.akita,
      jp-region.yamagata,
      jp-region.fukushima,
    ),
  ),
  東急・伊豆急・上田: (
    fill: "#e50012",
    coverage: (jp-region.tokyo, jp-region.kanagawa, jp-region.shizuoka, jp-region.nagano),
  ),
  東武・上毛: (
    fill: "#002e6e",
    coverage: (
      jp-region.tokyo,
      jp-region.chiba,
      jp-region.saitama,
      jp-region.tochigi,
      jp-region.gunma,
      jp-region.ibaraki,
    ),
  ),
  東海: (
    fill: "#ff6600",
    coverage: (jp-region.shizuoka, jp-region.aichi, jp-region.gifu, jp-region.mie),
  ),
  甲信越: (
    fill: "#007b43",
    coverage: (jp-region.yamanashi, jp-region.nagano, jp-region.niigata),
  ),
  相鉄: (
    fill: "#003ca2",
    coverage: (jp-region.kanagawa, jp-region.tokyo),
  ),
  私鉄貨物: (
    fill: "#595959",
    coverage: (
      jp-region.iwate,
      jp-region.fukushima,
      jp-region.ibaraki,
      jp-region.saitama,
      jp-region.kanagawa,
      jp-region.niigata,
      jp-region.toyama,
      jp-region.mie,
      jp-region.fukuoka,
    ),
  ),
  西武・伊豆箱・近江: (
    fill: "#0096cc",
    coverage: (jp-region.tokyo, jp-region.saitama, jp-region.kanagawa, jp-region.shizuoka, jp-region.shiga),
  ),
  西鉄・筑豊: (
    fill: "#e60012",
    coverage: (jp-region.fukuoka,),
  ),
  近鉄系: (
    fill: "#e60012",
    coverage: (jp-region.osaka, jp-region.nara, jp-region.kyoto, jp-region.mie, jp-region.aichi, jp-region.gifu),
  ),
  関東: (
    fill: "#ff7c00",
    coverage: (
      jp-region.tokyo,
      jp-region.kanagawa,
      jp-region.chiba,
      jp-region.saitama,
      jp-region.ibaraki,
      jp-region.tochigi,
      jp-region.gunma,
    ),
  ),
  関西: (
    fill: "#0067b1",
    coverage: (jp-region.osaka, jp-region.hyogo, jp-region.kyoto, jp-region.shiga, jp-region.nara, jp-region.wakayama),
  ),
  阪急・能勢・神鉄: (
    fill: "#800000",
    coverage: (jp-region.osaka, jp-region.hyogo, jp-region.kyoto),
  ),
  阪神・山陽: (
    fill: "#f39800",
    coverage: (jp-region.osaka, jp-region.hyogo),
  ),
  スロープカー: (
    fill: "#8dc63f",
    coverage: (
      jp-region.hokkaido,
      jp-region.aomori,
      jp-region.iwate,
      jp-region.miyagi,
      jp-region.akita,
      jp-region.fukushima,
      jp-region.ibaraki,
      jp-region.tochigi,
      jp-region.gunma,
      jp-region.saitama,
      jp-region.chiba,
      jp-region.tokyo,
      jp-region.kanagawa,
      jp-region.niigata,
      jp-region.toyama,
      jp-region.ishikawa,
      jp-region.fukui,
      jp-region.yamanashi,
      jp-region.nagano,
      jp-region.gifu,
      jp-region.shizuoka,
      jp-region.aichi,
      jp-region.mie,
      jp-region.shiga,
      jp-region.kyoto,
      jp-region.osaka,
      jp-region.hyogo,
      jp-region.nara,
      jp-region.wakayama,
      jp-region.tottori,
      jp-region.okayama,
      jp-region.hiroshima,
      jp-region.yamaguchi,
      jp-region.tokushima,
      jp-region.kagawa,
      jp-region.ehime,
      jp-region.kochi,
      jp-region.fukuoka,
      jp-region.saga,
      jp-region.nagasaki,
      jp-region.kumamoto,
      jp-region.oita,
      jp-region.miyazaki,
      jp-region.kagoshima,
      jp-region.okinawa,
    ),
  ),
)
