name: Build and Deploy Site

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v20
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: Cache Output Directory
        id: db-cache
        uses: actions/cache@v4
        with:
          path: ./output
          key: ${{ runner.os }}-db-${{ hashFiles('db_version') }}

      - name: Rebuild Index
        if: steps.db-cache.outputs.cache-hit != 'true'
        run: nix develop .#default --command ./scrape.py

      - name: Build site
        run: |
          nix develop .#default --command sh -c "tree -Jf output/* > data.json"
          nix develop .#default --command ./dist.typ --input root="tfvindex/"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: icons
          path: output

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist/tfvindex"
      - uses: actions/deploy-pages@v4
